on:
  push:

  pull_request:

  workflow_dispatch:

name: Ansible modules ganeti

jobs:
  test:
    name: "Test Ansible Modules"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install requirements
      run: |
            sudo apt update && sudo apt install python3 python3-pip python3-setuptools python3-pycurl python3-simplejson
            sudo -H pip3 install pytest pytest-mock ansible

    - name: Pull the ganeti fake cluster docker image
      run: docker pull ghcr.io/sipgate/ganeti-docker:latest

    - name: Startup the ganeti fake cluster
      run: |
            docker run -d -p 5080:5080 --cap-add=NET_ADMIN ghcr.io/sipgate/ganeti-docker:latest

    - name: Wait till the fake cluster and the ganeti RAPI is up and running
      run: n=0; until [ "$n" -ge 60 ]; do curl --output /dev/null --silent --fail --insecure https://localhost:5080/2/info && break; n=$((n+1)); sleep 5; done

    - name: Test - retrieve cluster info from RAPI
      run: curl --insecure https://localhost:5080/2/info

    - name: Run tests for python modules
      run: pytest
