---
name: "Test Ansible Module"
on:
  push:

  pull_request:

  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Pull image
      run: docker pull ghcr.io/sipgate/ansible-modules-ganeti-test:latest

    - name: Run image
      run: docker run --rm -v .:/workdir --net=host -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/sipgate/ansible-modules-ganeti-test:latest
